

application:
  name: "WeGPT"
  version: 1.0
  
database:
  name: "mysql"
  host: "host.docker.internal"
  port: 3306
  pass: "quantMoso161405202322"
  user: "root"

smsCode:
  signName: "竹指"
  templateCode: "SMS_272660653"